### ISSUE TITLE
[Bug]: clean install fails if choosing 'shopify' integration

### ISSUE THREAD

**Issue by samijaber** [vuestorefront/vue-storefront#6600]
### Describe the Bug

A fresh new install of `vue-storefront` doesn't work if Ifollow the instructions in https://docs.vuestorefront.io/v2/general/installation.html, and use `shopify` as the chosen integration.

### Current behavior

Running `yarn run` yields this:
![image](https://user-images.githubusercontent.com/1393142/148607381-a8e51510-32d1-4931-804c-b0c59d757e1b.png)
![image](https://user-images.githubusercontent.com/1393142/148607407-ff473914-0c94-46b4-b85d-3eee9e806303.png)

### Expected behavior

For `yarn run` to work properly with no errors.

### What version of Vue Storefront are you using?

latest (2.5.4?)

### What version of Node.js are you using?

16.3.1

### What browser (and version) are you using?

Brave/Chrome/Safari

### What operating system (and version) are you using?

macOS

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samijaber** [comment]
I have narrowed down the issue to the `RelatedProducts` component (or its data). Commenting out this code causes the build to pass:

https://github.com/vuestorefront/template-shopify/blob/59922eb408b3249a35bff378214e1f9e896a4462/pages/Home.vue#L31-L35

**Comment by jeffpdotone** [comment]
@samijaber could you also share a dummy snapshot of what data being fetch from here? I was trying to replicate this one but I couldn't with my own shopify instance.

**Comment by jeffpdotone** [comment]
@samijaber We've released a minor version update can you update your vue-storefront/shopify to version 1.0.10. Let me know if this works for your end.

**Comment by jeffpdotone** [comment]
Fixed by vuestorefront/shopify#146

**Comment by eduardoperez2151** [comment]
Hi @jeffpdotone & @samijaber I created a clean init and the problem still happens.

**Comment by conesplitter** [comment]
Hello, I am also experiencing this problem, I just tried agian with the CLI and the problem is still there
